language: php

php:
  - 7.0

sudo: false

env:
  - APP_DEBUG=false

service:
  - mysql

before_script:
  - mysql -e 'create database test;'

install:
  - composer install --prefer-dist --optimize-autoloader --quiet
  - php artisan migrate --force
  - php artisan db:seed --force

script: phpunit -c phpunit.xml --coverage-text

env:
  - DB_DATABASE=test DB_USERNAME=root DB_PASSWORD=